language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    

before_script:
    - phpenv rehash
    - composer install --dev

script:
    - find ./ -path ./vendor -prune -o  -name "*.php" -exec php -l {} \;
    - vendor/bin/phpcs --standard=PSR2 --report=full --ignore=./vendor/*.*,./Tests/*.* .
    - vendor/bin/phpunit
